---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml

secretGenerator:
- name: bitwarden-access-token
  type: Opaque
  envs:
  - bitwarden-token.env

generatorOptions: # see https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#generatoroptions
  disableNameSuffixHash: true # disable hash suffix
  labels:
    type: generated
  annotations:
    note: generated