apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-oidc-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: CLIENT_ID
    remoteRef:
      key: "traefik-clientID"
  - secretKey: CLIENT_SECRET
    remoteRef:
      key: "traefik-clientSecret"
  - secretKey: SESSION_SECRET
    remoteRef:
      key: "traefik-oidc-session-secret"
