apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
  - secretKey: CLIENT_ID
    remoteRef:
      key: "OIDC-Client-ID"
  - secretKey: CLIENT_SECRET
    remoteRef:
      key: "OIDC-Client-Secret"
  - secretKey: COOKIE_SECRET
    remoteRef:
      key: "OIDC-Cookie-Secret"