namespace: uat
namePrefix: uat-
nameSuffix: "-001"
resources:
  - ../../base
patches:
 - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: photography-web-ingress
   path: ingress-patch.yaml