apiVersion: v1
clusters:
- cluster:
    server: https://k8s-api.lucascajal.com
  name: kind-pi5
contexts:
- context:
    cluster: kind-pi5
    user: kind-pi5
  name: kind-pi5
current-context: kind-pi5
kind: Config
preferences: {}
users:
- name: kind-pi5
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://lucascajal.eu.auth0.com/
        - --oidc-client-id=KWdIwT2ckCdAOfRmo54iXHnfotkv4r3r
        - --oidc-extra-scope=openid
        - --oidc-extra-scope=profile
        - --oidc-extra-scope=offline_access
