---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oauth2-proxy

resources:
  - namespace.yaml

secretGenerator:
- name: oidc-secret
  type: Opaque
  envs:
  - oidc-secret.env

generatorOptions: # see https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#generatoroptions
  disableNameSuffixHash: true # disable hash suffix
  labels:
    type: generated
  annotations:
    note: generated