apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --oidc-issuer-url=https://lucascajal.eu.auth0.com/
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --set-authorization-header=true # Set auth header
        - --pass-authorization-header=true # Pass auth header to upstream

        # See complete list of options at https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#config-options
        # - --scope=openid groups profile email
        # - --upstream=static://200
        # - --insecure-oidc-allow-unverified-email=true # see https://github.com/oauth2-proxy/oauth2-proxy/issues/1712
        # - --code-challenge-method=S256
        # - --pass-access-token=true
        # - --set-xauthrequest=true
        # - --cookie-expire=0 # expire cookies on browser close
        # - --cookie-name=__Host-
        # - --pass-user-headers=true
        # - --pass-host-header=true
        # - --skip-jwt-bearer-tokens=true
        # - --redirect-url="https://dashboard-test.lucascajal.com/oauth2/callback"
        # - --reverse-proxy=true
        # - --skip-provider-button=true
        # - --upstream=https://lucascajal.com

        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oidc-secret
              key: CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-secret
              key: CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-secret
              key: COOKIE_SECRET
        # Recommended: remove email-domain=* in args and set an allowlist
        # - name: OAUTH2_PROXY_GITHUB_USERS
        #   value: alice,bob

        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi