---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml

# OIDC secret
secretGenerator:
- name: oidc-secret
  type: Opaque
  envs:
  - oidc-secret.env
generatorOptions: # see https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#generatoroptions
  disableNameSuffixHash: true # disable hash suffix
  labels:
    type: generated
  annotations:
    note: generated