---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

secretGenerator:
- name: auth0
  envs:
  - secret-auth0.env
  type: Opaque


generatorOptions: # see https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#generatoroptions
  disableNameSuffixHash: true # disable hash suffix
  labels:
    type: generated
    app.kubernetes.io/part-of:  argocd
  annotations:
    note: generated