namespace: prod
namePrefix: prod-
nameSuffix: "-001"
resources:
  - ../../base
patches:
 - target:
      group: apps
      version: v1
      kind: Deployment
      name: helloworld-app
   path: deployment-patch.yaml