---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - externalsecret.yaml
  - podmonitor.yaml
  - grafana-dashboard.yaml
  - grafana-dashboard-advanced.yaml
  - vpa.yaml

# Generate config
configMapGenerator:
- name: cloudflared
  files:
  - config.yaml

generatorOptions: # see https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#generatoroptions
  disableNameSuffixHash: true # disable hash suffix
  labels:
    type: generated
  annotations:
    note: generated