---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: cert-manager
    spec:
      destination:
        name: "{{cluster}}"
        namespace: cert-manager
      project: default
      sources:
        - chart: cert-manager
          repoURL: https://charts.jetstack.io
          targetRevision: v1.17.0
          helm:
            releaseName: cert-manager
            values: |
              crds:
                enabled: true

              resources:
                requests:
                  cpu: 15m
                  memory: 50Mi
                limits:
                  cpu: 40m
                  memory: 100Mi

              cainjector:
                resources:
                  requests:
                    cpu: 15m
                    memory: 75Mi
                  limits:
                    cpu: 40m
                    memory: 150Mi

              webhook:
                resources:
                  requests:
                    cpu: 15m
                    memory: 35Mi
                  limits:
                    cpu: 40m
                    memory: 80Mi

        - path: cluster-resources/cert-manager
          repoURL: https://github.com/lucascajal/k8s-playground.git
          targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            goldilocks.fairwinds.com/enabled: "true"
