---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: cloudflared
    spec:
      destination:
        name: "{{cluster}}"
        namespace: tunnel-cloudflared
      project: default
      source:
        path: cluster-resources/cloudflared
        repoURL: https://github.com/lucascajal/k8s-playground.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            goldilocks.fairwinds.com/enabled: "true"
