---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: external-secrets
    spec:
      destination:
        name: "{{cluster}}"
        namespace: external-secrets
      project: default
      sources:
        - chart: external-secrets
          repoURL: https://charts.external-secrets.io
          targetRevision: v0.18.2
          helm:
            releaseName: external-secrets
            parameters:
              - name: bitwarden-sdk-server.enabled
                value: "true"
        - path: cluster-resources/external-secrets
          repoURL: https://github.com/lucascajal/k8s-playground.git
          targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
