---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-operator
  # annotations:
  #   argocd.argoproj.io/sync-wave: "10"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: prometheus-operator
    spec:
      destination:
        name: "{{cluster}}"
        namespace: prometheus-system
      project: default
      sources:
      - chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: "75.16.1"
        helm:
          releaseName: kube-prometheus-stack
          values: |
            crds:
              enabled: true

            # Keep kubelet/cAdvisor on (dashboards need container metrics), but trim extras.
            kubelet:
              serviceMonitor:
                # Still scrape /metrics and /metrics/cadvisor for dashboards.
                cAdvisor: true
                probes: false        # drop /metrics/probes (not needed)
                resource: false      # drop /metrics/resource (not needed)
                metricRelabelings:
                  # Drop very high-cardinality labels that dashboards don't use.
                  - action: labeldrop
                    regex: (container_id|container_image|container_image_id|image|pod_uid)

            # Disable Alertmanager to save RAM/CPU.
            alertmanager:
              enabled: false

            prometheus:
              # ingress:
              #   enabled: true
              #   ingressClassName: nginx
              #   hosts:
              #     - prometheus.lucascajal.com
              #   paths:
              #     - /
              #   pathType: Prefix

              prometheusSpec:
                scrapeInterval: 60s
                evaluationInterval: 60s
                retention: 12h
                retentionSize: 1GiB
                walCompression: true
                # Limit per-target samples to prevent accidental blowups.
                enforcedSampleLimit: 5000
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi

            grafana:
              resources:
                requests:
                  cpu: 50m
                  memory: 160Mi
                limits:
                  cpu: 300m
                  memory: 384Mi

              # Disable features that add overhead.
              imageRenderer:
                enabled: false
              unified_alerting:
                enabled: false

              sidecar:
                dashboards:
                  enabled: true
                datasources:
                  enabled: true

              envFromSecret: auth0-grafana

              grafana.ini:
                # Reduce query pressure and background work.
                dashboards:
                  min_refresh_interval: 30s
                analytics:
                  reporting_enabled: false
                  check_for_updates: false

                server:
                  root_url: https://grafana.lucascajal.com

                auth:
                  disable_login_form: true
                  oauth_auto_login: false

                auth.basic:
                  enabled: false

                auth.generic_oauth:
                  enabled: true
                  name: Auth0
                  allow_sign_up: true
                  role_attribute_strict: true
                  use_pkce: true
                  use_refresh_token: true
                  auth_url: https://lucascajal.eu.auth0.com/authorize
                  token_url: https://lucascajal.eu.auth0.com/oauth/token
                  api_url: https://lucascajal.eu.auth0.com/userinfo
                  scopes: openid profile email
                  email_attribute_path: email
                  login_attribute_path: email
                  name_attribute_path: name
                  # Map Auth0 roles to Grafana roles
                  role_attribute_path: >-
                    contains("lucascajal.com/roles", 'grafana-admin') && 'Admin' ||
                    contains("lucascajal.com/roles", 'grafana-editor') && 'Editor' ||
                    contains("lucascajal.com/roles", 'grafana-viewer') && 'Viewer' ||
                    'None'
                  allow_assign_grafana_admin: true

            #   ingress:
            #     enabled: true
            #     ingressClassName: nginx
            #     hosts:
            #       - grafana.lucascajal.com
            #     path: /
            #     pathType: Prefix
      - path: cluster-resources/prometheus
        repoURL: https://github.com/lucascajal/k8s-playground.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          # - Replace=true
          - ServerSideApply=true