---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vpa-fairwinds-goldilocks
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: vpa-fairwinds-goldilocks
    spec:
      destination:
        name: "{{cluster}}"
        namespace: vpa-goldilocks
      project: default
      sources:
      - chart: goldilocks
        repoURL: https://charts.fairwinds.com/stable
        targetRevision: 10.1.0
        helm:
          releaseName: goldilocks
          values: |
            dashboard:
              enabled: false
              replicaCount: 1
              ingress:
                enabled: true
                ingressClassName: nginx
                hosts:
                  - host: goldilocks.lucascajal.com
                    paths:
                      - path: /
                        type: ImplementationSpecific
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            goldilocks.fairwinds.com/enabled: "true"