apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsreaders-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsreaders-frontend
  template:
    metadata:
      labels:
        app: newsreaders-frontend
    spec:
      imagePullSecrets:
      - name: container-registry-credentials # Secret containing the GitLab registry credentials
      containers:
      - name: newsreaders-frontend
        image: registry.gitlab.com/lucascajal1/k8s/newsreaders-frontend:latest
        env:
        - name: API_HOST
          value: "http://newsreaders-backend-service"
        - name: API_PORT
          value: "80"
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsreaders-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsreaders-backend
  template:
    metadata:
      labels:
        app: newsreaders-backend
    spec:
      imagePullSecrets:
      - name: container-registry-credentials # Secret containing the GitLab registry credentials
      containers:
      - name: newsreaders-backend
        image: registry.gitlab.com/lucascajal1/k8s/newsreaders-backend:latest
        env:
        - name: REDIS_HOST
          value: "newsreaders-redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsreaders-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsreaders-redis
  template:
    metadata:
      labels:
        app: newsreaders-redis
    spec:
      containers:
      - name: newsreaders-redis
        image: redis:7.2-alpine
