---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - ingress.yaml
  # - blog.yaml
  - migration-helper.yaml
  - newsreaders.yaml
  # - photography-web.yaml