apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth0
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: clientID
    remoteRef:
      key: "argocd-clientID"
  - secretKey: clientSecret
    remoteRef:
      key: "argocd-clientSecret"