---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.2/deploy/static/provider/baremetal/deploy.yaml

patches:
  - target: # Set it to CLusterIP as the cluster is not exposed, with all traffic going through cloudflared
      kind: Service
      name: ingress-nginx-controller
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: ingress-nginx-controller
      spec:
        type: ClusterIP

  - target: # Change the resources request
      kind: Deployment
      name: ingress-nginx-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ingress-nginx-controller
      spec:
        replicas: 4
        template:
          spec:
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "kubernetes.io/hostname"
              whenUnsatisfiable: DoNotSchedule # ScheduleAnyway
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: controller
                  app.kubernetes.io/instance: ingress-nginx
                  app.kubernetes.io/name: ingress-nginx
            containers:
              - name: controller
                livenessProbe:
                  failureThreshold: 15
                  initialDelaySeconds: 15
                  periodSeconds: 30
                readinessProbe:
                  failureThreshold: 10
                  initialDelaySeconds: 15
                  periodSeconds: 10
                resources:
                  requests:
                    cpu: "15m"
                    memory: "75Mi"
                  limits:
                    cpu: "50m"
                    memory: "200Mi"
            tolerations: # For taint architecture=armv7:NoSchedule
            - key: "architecture"
              operator: "Equal"
              value: "armv7"
              effect: "NoSchedule"

  # Fix for missing jobs after they complete due to the ttlSecondsAfterFinished: 0
  # Option 1: Use hooks (actually removes them using ArgoCD, but runs on every sync op)
  - target:
      kind: Job
      name: ingress-nginx-admission-create
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ingress-nginx-admission-create
        annotations:
          argocd.argoproj.io/hook: Sync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
  - target:
      kind: Job
      name: ingress-nginx-admission-patch
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ingress-nginx-admission-patch
        annotations:
          argocd.argoproj.io/hook: Sync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
  # Option 2: Remove TTL (does not remove the job, it stays indefinitely in the cluster)
  # - target:
  #     kind: Job
  #     name: ingress-nginx-admission-create
  #   patch: |-
  #     - op: remove
  #       path: /spec/ttlSecondsAfterFinished
  # - target:
  #     kind: Job
  #     name: ingress-nginx-admission-patch
  #   patch: |-
  #     - op: remove
  #       path: /spec/ttlSecondsAfterFinished