---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.2/deploy/static/provider/baremetal/deploy.yaml

patches:
  - target: # Set it to CLusterIP as the cluster is not exposed, with all traffic going through cloudflared
      kind: Service
      name: ingress-nginx-controller
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: ingress-nginx-controller
      spec:
        type: ClusterIP

  - target: # Change the resources request
      kind: Deployment
      name: ingress-nginx-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ingress-nginx-controller
      spec:
        replicas: 4
        template:
          spec:
            containers:
              - name: controller
                resources:
                  requests:
                    cpu: "30m"
                    memory: "60Mi"
                  limits:
                    cpu: "200m"
                    memory: "256Mi"

  - target: # Add fairwinds VPA label
      kind: Namespace
      name: ingress-nginx
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ingress-nginx
        labels:
          app.kubernetes.io/instance: ingress-nginx
          app.kubernetes.io/name: ingress-nginx
          goldilocks.fairwinds.com/enabled: "true"

  # Fix for missing jobs after they complete due to the ttlSecondsAfterFinished: 0
  # Option 1: Use hooks (actually removes them using ArgoCD, but runs on every sync op)
  - target:
      kind: Job
      name: ingress-nginx-admission-create
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ingress-nginx-admission-create
        annotations:
          argocd.argoproj.io/hook: Sync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
  - target:
      kind: Job
      name: ingress-nginx-admission-patch
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: ingress-nginx-admission-patch
        annotations:
          argocd.argoproj.io/hook: Sync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
  # Option 2: Remove TTL (does not remove the job, it stays indefinitely in the cluster)
  # - target:
  #     kind: Job
  #     name: ingress-nginx-admission-create
  #   patch: |-
  #     - op: remove
  #       path: /spec/ttlSecondsAfterFinished
  # - target:
  #     kind: Job
  #     name: ingress-nginx-admission-patch
  #   patch: |-
  #     - op: remove
  #       path: /spec/ttlSecondsAfterFinished