apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: container-registry-credentials
spec:
  externalSecretName: "container-registry-credentials"
  namespaceSelectors:
  # - matchLabels:
  #     cool: label
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
        - default
        - tunnel-cloudflared
        - raspotify
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: bitwarden-secretsmanager
      kind: ClusterSecretStore
    target:
      template:
        type: kubernetes.io/dockerconfigjson
    data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: "container-registry-creds"