namespace: dev
namePrefix: dev-
nameSuffix: "-001"
resources:
  - ../../base
patches:
 - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: helloworld-ingress
   path: ingress-patch.yaml