apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: private-repo-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  dataFrom:
  - extract:
      key: argocd-github-repos-read
