---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blog
  annotations:
    argocd.argoproj.io/sync-wave: "140"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: blog
    spec:
      destination:
        name: "{{cluster}}"
        namespace: blog
      project: personal
      source:
        path: apps/blog/base
        repoURL: https://github.com/lucascajal/k8s-playground.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
