---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - blog.yaml
  # - dashboard.yaml
  # - migration-helper.yaml
  - newsreaders.yaml
  - photography-web.yaml
  - surf-alert.yaml
  - raspotify.yaml
