---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: surf-alert
  annotations:
    argocd.argoproj.io/sync-wave: "140"
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: surf-alert
    spec:
      destination:
        name: "{{cluster}}"
        namespace: surf-alert
      project: personal
      source:
        path: k8s
        repoURL: https://github.com/lucascajal/surf-alert.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
