apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth0-grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: kube-prometheus-stack
  data:
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    remoteRef:
      key: "grafana-clientID"
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    remoteRef:
      key: "grafana-clientSecret"