---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - https://github.com/lucascajal/k8s-playground.git
  - https://kubernetes.github.io/dashboard/
  - https://charts.jetstack.io # cert-manager
  - https://charts.external-secrets.io
  - https://kubernetes-sigs.github.io/metrics-server
  - https://prometheus-community.github.io/helm-charts
