---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: personal
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - https://github.com/lucascajal/k8s-playground.git
  - https://github.com/lucascajal/surf-alert.git
