apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newsreaders
  namespace: argocd
  # finalizers: # See https://argo-cd.readthedocs.io/en/release-2.14/user-guide/app_deletion/#about-the-deletion-finalizer
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: 'apps/newsreaders/base'
    repoURL: 'https://github.com/lucascajal/k8s-playground.git'
    targetRevision: HEAD
  sources: []
  project: default

  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true